Feature: VisitDonorPages
    Scenario: I can visit the funds pages
        Given I am logged in as admin
        When I visit "Add Task"
        Then the page should say "Create Task"
        And the URL should contain "/erp/me/task/create"
        When I visit "Reports"
        Then the page should say "Reports"
        And the URL should contain "/erp/report/funit"
        When I visit "Transfer Money"
        Then the page should say "Accounts"
        And the URL should contain "/erp/account/transfer/quick"
        When I visit "List"
        Then the page should say "Funds"
        And the URL should contain "/erp/funit/list"
        When I visit "List DAFs"
        Then the page should say "Funds"
        And the URL should contain "/erp/funit/list"
        When I visit "List Agency"
        Then the page should say "Funds"
        And the URL should contain "/erp/funit/list"
        When I visit "List Affiliate"
        Then the page should say "Funds"
        And the URL should contain "/erp/funit/list"
        When I visit "List Promoted"
        Then the page should say "Funds"
        And the URL should contain "/erp/funit/list"
        When I visit "List Groups"
        Then the page should say "Fund Groups"
        And the URL should contain "/erp/funit/list/group"
        When I visit "Grant Approvers"
        Then the page should say "Grant Approvers"
        And the URL should contain "/erp/funit/edit_grant_approvers"
        When I visit "Bulk Edit"
        Then the page should say "Bulk Edit Funds"
        And the URL should contain "/erp/funit/edit/bulk"
        When I visit "Create"
        Then the page should say "Create Fund"
        And the URL should contain "/erp/funit/create"
        When I visit "Fund Statements"
        Then the page should say "Fund Statements"
        And the URL should contain "/erp/funit/statement"
        When I visit "Distributions"
        Then the page should say "Distributions"
        And the URL should contain "/erp/distribution/list"
        When I visit "Clear Spendable"
        Then the page should say "Clear Spendable"
        And the URL should contain "/erp/distribution/delete/clearspendable"
        When I visit "Distribution Types"
        Then the page should say "Distribution Types"
        And the URL should contain "/erp/distribution/list/type"
        When I visit "Create Spendable Grants"
        Then the page should say "Create Spendable Grants"
        And the URL should contain "/erp/grant/create/spendable"
        When I visit "Fund Fee Types"
        Then the page should say "Fund Fee Types"
        And the URL should contain "/erp/funit/feetype"
        When I visit "Admin Fee Groups"
        Then the page should say "Admin Fee Groups"
        And the URL should contain "/erp/funit/feetype/group"
        When I visit "Balance Swap"
        Then the page should say "Cash Balancing Fund"
        And the URL should contain "/erp/funit/display"
        When I visit "Permission"
        Then the page should say "Manage Access"
        And the URL should contain "/erp/funit/permission"