Feature: VisitDonorPages
    Scenario: I can visit the donor pages
        Given I am logged in as admin
        When I visit "Donors"
        Then the page should say "Donor"
        And the URL should contain "/doner"
        When I visit "Add Task"
        Then the page should say "Me"
        And the URL should contain "/me/task/create?task_o=doner"
        When I visit "List"
        Then the page should say "Profiles"
        And the URL should contain "/profile/list/list?is=doner"
        When I visit "Reports"
        Then the page should say "Reports"
        And the URL should contain "/report/doner"
        When I visit "Create"
        Then the page should say "Profiles"
        And the URL should contain "/profile/list"
        When I visit "Tax Receipt Jobs"
        Then the page should say "Donors"
        And the URL should contain "/doner/display/jobs?doner_id="
        When I visit "Permission"
        Then the page should say "Donors"
        And the URL should contain "/doner/permission"